# Number of replicas for the application
replicaCount: 1

image:
  repository: saadrehman17100/myapp-image  # Docker image for the application
  tag: latest  # Image tag
  pullPolicy: Always  # Always pull the latest image

serviceAccount:
  create: true  # Creates a new service account
  name: myapp-sa  # Name of the service account

podAnnotations: {}  # Annotations for the pods

podLabels: {}  # Labels for the pods

securityContext: {}  # Pod security context
containerSecurityContext: {}  # Container security context

service:
  type: ClusterIP  # Internal service type to expose within the cluster
  port: 3000  # This is the external port (ingress) that users will hit

ingress:
  enabled: true  # Enable Ingress for external access
  className: "nginx"  # Ingress controller class
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: myapp.local  # Host for the application
      paths:
        - path: /  # Path that Ingress will route
          pathType: Prefix
  tls: []  # TLS configuration, left empty for now

resources: {}  # Resource limits and requests for the pods

autoscaling:
  enabled: false  # Autoscaling disabled for now
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 100  # Maximum number of replicas
  targetCPUUtilizationPercentage: 80  # Autoscale based on 80% CPU utilization

nodeSelector: {}  # Node selection configuration, left empty

tolerations: []  # Tolerations for scheduling, left empty

affinity: {}  # Affinity rules for pod placement, left empty
